apiVersion: apps/v1
kind: Deployment
metadata:
  name: webuoc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webuoc
  template:
    metadata:
      labels:
        app: webuoc
    spec:
      containers:
      - name: webuoc
        image: mi-web-uoc:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
