apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-web-uoc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-uoc
  template:
    metadata:
      labels:
        app: web-uoc
    spec:
      containers:
      - name: nginx
        image: mi-web-uoc:latest
        imagePullPolicy: Never # Importante para que use la imagen local que compiló Jenkins
        ports:
        - containerPort: 80
