apiVersion: v1
kind: Service
metadata:
  name: webuoc-service
spec:
  type: NodePort
  selector:
    app: webuoc
  ports:
    - protocol: TCP
      port: 80          # puerto del servicio
      targetPort: 80    # puerto del contenedor
      nodePort: 30008   # puerto externo (30000-32767)
